[package]
name = "cow-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "0.12.6"
eyre = "0.6.12"
hex = "0.4.3"
reqwest = "0.12.15"
secp256k1 = "0.30.0"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
serde_urlencoded = "0.7.1"
tokio = "1.44.1"
url = "2.5.4"
